### ISSUE TITLE
Sparse matrices for graph linear algebra

### ISSUE THREAD

**Issue by breandan** [amodeus-science/tensor#1]
Hi Jan and Claudio, 

Hope you are both well! I have been following your work closely and am curious to know if tensor plans to support, or is willing to accept PRs for sparse (e.g. CSR/CSC) matrix and tensor arithmetic? Do you anticipate this would be difficult to implement using the current API? I would like to use it for [spectral graph theory](https://www.cs.yale.edu/homes/spielman/sagt/sagt.pdf), which borrows many techniques from linear algebra (e.g. EVD, power iteration, Newton's method) to study network dynamical processes. Are you familiar with [SuiteSparse](http://faculty.cse.tamu.edu/davis/suitesparse.html) and the [GraphBLAS](http://www.mit.edu/~kepner/GraphBLAS/GraphBLAS-Math-release.pdf) project? I believe the techniques they are developing could have many useful applications for AMoD, and would allow your traffic simulator to process much larger transportation networks in memory. Also happy to discuss their applications for MDPs and other labeled transition systems. Thank you.

Best regards,

Breandan

**Comment by datahaki** [comment]
>  is willing to accept PRs for sparse (e.g. CSR/CSC) matrix and tensor arithmetic?

yes, under the condition that modifications 1) do not brake anything substantial, and 2) do not require the introduction of a license.

looking forward to see your implementation!

**Comment by breandan** [comment]
Thanks! Don’t plan to break anything or need any license changes. I’ll start working from a fork and submit a PR when it’s ready to review.
